"""Static checks for the backend-mounted workbench shell."""

from __future__ import annotations

import unittest
from pathlib import Path


class WorkbenchStaticAssetsTest(unittest.TestCase):
    def test_workbench_uses_backend_mounted_asset_paths(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")

        self.assertIn('href="/frontend/styles.css?v=20260526-project-move-menu"', html)
        self.assertIn('href="/frontend/favicon.svg"', html)
        self.assertIn('src="/frontend/app.js?v=20260526-project-move-menu"', html)
        self.assertNotIn('href="./styles.css"', html)
        self.assertNotIn('src="./app.js"', html)

    def test_workbench_assets_are_cache_busted_and_not_cached_by_backend(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")
        backend = Path("backend/main.py").read_text(encoding="utf-8")

        self.assertIn("?v=20260526-project-move-menu", html)
        self.assertIn("NO_CACHE_HEADERS", backend)
        self.assertIn('"Cache-Control": "no-store, max-age=0"', backend)
        self.assertIn('"Pragma": "no-cache"', backend)
        self.assertIn('"Expires": "0"', backend)
        self.assertIn("class NoCacheStaticFiles(StaticFiles)", backend)
        self.assertIn("headers=NO_CACHE_HEADERS", backend)

    def test_runtime_sync_preserves_workbench_storage(self) -> None:
        script = Path("scripts/sync_workbench_runtime.sh").read_text(encoding="utf-8")

        self.assertIn('--exclude "/storage/"', script)
        self.assertNotIn('--exclude "storage"', script)
        self.assertIn("--delete", script)

    def test_workbench_chart_svg_overrides_global_icon_svg_size(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")

        self.assertIn("const displayValues = values.slice(0, horizontal ? 18 : 16)", js)
        self.assertIn("420 / displayValues.length", js)
        self.assertIn(".chart-svg", css)
        self.assertIn("height: auto;", css)
        self.assertIn("max-height: none;", css)
        self.assertIn("min-height: 230px;", css)

    def test_workbench_prefers_backend_rendered_chart_images(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")
        render_chart = js.split("function renderChart", 1)[1].split("function renderChartImage", 1)[0]

        self.assertIn("chart?.image_data_uri", js)
        self.assertIn("renderChartImage", js)
        self.assertLess(render_chart.index("chart?.image_data_uri"), render_chart.index("const y = resolveChartY"))
        self.assertIn('class="chart-image"', js)
        self.assertIn("function resolveChartY", js)
        self.assertIn(".chart-image", css)
        self.assertIn("object-fit: contain;", css)

    def test_workbench_uses_chat_first_shell(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")

        self.assertIn('aria-label="历史 Chat"', html)
        self.assertIn('id="chat-messages"', html)
        self.assertIn('href="/monitor"', html)
        self.assertIn('class="composer-shell"', html)
        self.assertIn('class="composer-input is-empty"', html)
        self.assertIn('role="textbox"', html)
        self.assertIn('contenteditable="plaintext-only"', html)
        self.assertIn('data-placeholder="向 VDS 提问，例如：哪个城市订单金额最高？"', html)
        self.assertIn('spellcheck="false"', html)
        self.assertIn('data-ms-editor="false"', html)
        self.assertIn('data-enable-grammarly="false"', html)
        self.assertIn('class="upload-controls"', html)
        self.assertIn('id="upload-button"', html)
        self.assertIn('id="file-summary"', html)
        self.assertIn('id="file-panel"', html)
        self.assertIn('class="file-panel-list"', html)
        self.assertIn('accept=".csv,.xlsx,.xls,.json,.parquet,.arrow,.feather,.md,.txt,.yaml,.yml"', html)
        self.assertIn("上传数据文件，然后直接提问", html)
        self.assertIn("数据和说明文件支持多选", html)
        self.assertNotIn("高级选项", html)
        self.assertNotIn("启用 Rule Mode", html)
        self.assertNotIn("选择分析规则", html)
        self.assertNotIn("选择 Benchmark 规则", html)
        self.assertNotIn('class="upload-card"', html)
        self.assertNotIn('id="dropzone"', html)
        self.assertNotIn("<textarea", html)
        self.assertNotIn('class="work-grid"', html)
        self.assertNotIn('class="inspector"', html)

    def test_workbench_rule_package_support_stays_backend_routed_and_hidden_from_ui(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")
        js = Path("frontend/app.js").read_text(encoding="utf-8")

        self.assertIn('accept=".csv,.xlsx,.xls,.json,.parquet,.arrow,.feather,.md,.txt,.yaml,.yml"', html)
        self.assertNotIn("DAB 规则包", html)
        self.assertNotIn("DAB 规则包", js)
        self.assertIn('"/api/data-agent/upload-batch"', js)
        self.assertIn("renderFilePanel", js)
        self.assertIn("buildReadyFileRecords", js)
        self.assertIn("uniqueSourceFileNames", js)
        self.assertIn("点击查看文件", js)
        self.assertNotIn("fees.json", js)
        self.assertNotIn("merchant_data.json", js)
        self.assertNotIn("manual.md", js)

    def test_workbench_renders_backend_execution_artifacts(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")

        self.assertIn("artifact-panel", html)
        self.assertIn("artifact-list", html)
        self.assertIn("renderExecutionArtifacts", js)
        self.assertIn("result.execution_artifacts", js)
        self.assertIn("renderArtifactCards(artifacts)", js)
        self.assertIn("复现代码", js)
        self.assertIn("el.artifactPanel?.classList.add(\"hidden\")", js)
        self.assertIn(".artifact-card", css)
        self.assertIn(".artifact-list.inline", css)
        self.assertIn("white-space: pre-wrap", css)

    def test_workbench_suppresses_raw_detail_rows_for_general_questions(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")

        self.assertIn("function shouldRenderRows", js)
        self.assertIn('result.answer_type === "overview"', js)
        self.assertIn('result.answer_type === "cleaning_simulation"', js)
        self.assertIn("looksLikeGeneralQuestion", js)
        self.assertIn("tooWideForMainAnswer", js)
        self.assertIn("主要讲什么", js)
        self.assertIn("影响行数", js)
        self.assertIn(".insight-card", css)

    def test_workbench_hides_backend_audit_panels_from_user_shell(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")

        self.assertIn("分析过程", html)
        self.assertNotIn("数据质量", html)
        self.assertNotIn("Join / Verification", html)
        self.assertNotIn("Warnings / Errors", html)
        self.assertNotIn("source_tables", html)
        self.assertNotIn("join_plan", html)
        self.assertNotIn("dataset_id:", html)

    def test_workbench_renders_safe_process_evidence_from_backend(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")

        self.assertIn("normalizeProcessList(step.evidence", js)
        self.assertIn("renderProcessEvidence(step)", js)
        self.assertIn('aria-label="过程依据"', js)
        self.assertIn("connectActivityStream", js)
        self.assertIn("new EventSource", js)
        self.assertIn("/api/data-agent/monitor/stream?monitor_run_id=", js)
        self.assertIn("ACTIVITY_EVENT_TYPES", js)
        self.assertIn("code_artifact_ready", js)
        self.assertIn(".process-evidence", css)
        self.assertNotIn("buildFriendlySteps(processSource", js)

    def test_workbench_allows_chat_without_uploaded_dataset(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")

        self.assertIn('"/api/data-agent/message"', js)
        self.assertIn('answer_type === "chat"', js)
        self.assertNotIn("!state.datasetId || !question", js)
        self.assertNotIn('state.datasetId ? "/api/data-agent/analyze"', js)
        self.assertIn("当前没有上传数据，我会直接回复可讨论的部分，不编造业务结论。", js)

    def test_workbench_creates_one_assistant_result_per_turn(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")

        self.assertIn("createAssistantResultMessage", js)
        self.assertIn("cloneNode(true)", js)
        self.assertIn("assistant-result-message", js)
        self.assertIn(".assistant-message.thinking-only .result-panel", css)

    def test_workbench_enter_sends_and_shift_enter_keeps_newline(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")

        self.assertIn('addEventListener("keydown", handleQuestionKeydown)', js)
        self.assertIn('addEventListener("input", handleQuestionInput)', js)
        self.assertIn('addEventListener("paste", handleQuestionPaste)', js)
        self.assertIn('addEventListener("focus", updateQuestionEmptyState)', js)
        self.assertIn("getQuestionText()", js)
        self.assertIn("setQuestionText(\"\")", js)
        self.assertIn("updateQuestionEmptyState()", js)
        self.assertNotIn("questionInput.value", js)
        self.assertIn('event.key !== "Enter" || event.shiftKey || event.isComposing', js)
        self.assertIn("event.preventDefault()", js)
        self.assertIn("runAnalysis()", js)

    def test_workbench_history_items_can_be_renamed(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")

        self.assertIn("renderHistory()", js)
        self.assertIn("startHistoryRename", js)
        self.assertIn("commitHistoryRename", js)
        self.assertIn("handleHistoryRenameKeydown", js)
        self.assertIn("history-rename-button", js)
        self.assertIn("history-menu-button", js)
        self.assertIn("history-rename-input", js)
        self.assertIn("history-project-button", js)
        self.assertIn("history-delete-button", js)
        self.assertIn("history-pin-button", js)
        self.assertIn("toggleHistoryPinned", js)
        self.assertIn("renameConversationFromPrompt", js)
        self.assertIn("sortHistoryItems", js)
        self.assertIn("pinIcon", js)
        self.assertIn("openHistoryMenu", js)
        self.assertIn("buildProjectMoveItems", js)
        self.assertIn("renderContextSubmenu", js)
        self.assertIn("showContextSubmenu", js)
        self.assertIn("createProjectForHistory", js)
        self.assertIn("assignHistoryToProject", js)
        self.assertIn("deleteHistoryConversation", js)
        self.assertIn("body: JSON.stringify({ pinned: Boolean(pinned) })", js)
        self.assertIn('body: JSON.stringify({ project_id: safeProjectId })', js)
        self.assertNotIn("chooseProjectForHistory", js)
        self.assertNotIn("选择要移入的 Project", js)
        self.assertIn('method: "DELETE"', js)
        self.assertIn("markHistoryRunning", js)
        self.assertIn("acknowledgeHistoryItem", js)
        self.assertIn("unread: existing?.unread === true", js)
        self.assertIn("existingById", js)
        self.assertIn("localUnreadHistory", js)
        self.assertNotIn("已完成分析", js)
        self.assertNotIn("history-state", js)
        self.assertNotIn("hasVisibleState", js)
        self.assertNotIn("thinking-dot", js)
        self.assertIn('event.key === "Enter"', js)
        self.assertIn('event.key === "Escape"', js)
        self.assertIn("dataset.cancelRename", js)
        self.assertIn('input.addEventListener("blur"', js)
        self.assertIn('fetch(`/api/data-agent/conversations/${encodeURIComponent(runId)}`', js)
        self.assertIn(".history-item", css)
        self.assertIn(".history-item.active", css)
        self.assertIn("status-pill", css)
        self.assertIn(".button.primary:disabled", css)
        self.assertIn("background: #e5e7eb;", css)
        self.assertIn("border-color: #b8bbc7;", css)
        self.assertIn(".composer-input:empty::before", css)
        self.assertIn(".composer-input:empty", css)
        self.assertIn(".composer-input.is-empty", css)
        self.assertIn("caret-color: transparent;", css)
        self.assertIn("text-indent: -9999px;", css)
        self.assertIn("-webkit-text-fill-color: transparent;", css)
        self.assertIn(".composer-input:not(:empty)", css)
        self.assertIn("caret-color: #111827;", css)
        self.assertIn("grammarly-desktop-integration", css)
        self.assertIn("ms-editor-squiggler", css)
        self.assertNotIn("box-shadow: 0 18px 50px rgba(37, 99, 235", css)
        self.assertNotIn("status-dot", html)
        self.assertNotIn("status-dot", js)
        self.assertNotIn("status-spin", css)
        self.assertNotIn(".history-item.has-state", css)
        self.assertNotIn(".history-state", css)
        self.assertNotIn("thinking-dot", css)
        self.assertNotIn("step-dot", js)
        self.assertNotIn(".step-dot", css)
        self.assertIn(".history-menu-button", css)
        self.assertIn(".context-menu", css)
        self.assertIn(".context-submenu", css)
        self.assertIn(".context-menu-chevron", css)
        self.assertIn(".pin-indicator", css)
        self.assertIn(".history-rename-input", css)
        self.assertIn(".history-item.editing .history-title-row", css)

    def test_workbench_loads_persistent_conversations(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")

        self.assertIn("conversationId", js)
        self.assertIn("loadConversations()", js)
        self.assertIn("new URLSearchParams", js)
        self.assertIn("`/api/data-agent/conversations?${query.toString()}`", js)
        self.assertIn("loadConversation", js)
        self.assertIn("restoreConversation", js)
        self.assertIn("applyRestoredFileRecords(profile)", js)
        self.assertIn("clearRestoredFileRecords()", js)
        self.assertIn("state.fileRecords.length} 个文件已就绪", js)
        self.assertIn("需重新上传后继续分析", js)
        self.assertIn('item.last_answer_type === "chat" ? "chat" : "analysis"', js)
        self.assertIn("conversation_id: state.conversationId", js)
        self.assertIn("updateHistory: false", js)
        self.assertIn("pinned: Boolean(item.pinned)", js)
        self.assertIn("pinnedAt: item.pinned_at ||", js)
        global_loader = js[js.index("async function loadConversations()") : js.index("async function loadConversation(")]
        self.assertNotIn('query.set("project_id"', global_loader)
        self.assertNotIn('new URLSearchParams({ limit: "30", project_id', global_loader)
        self.assertIn("loadProjectConversations", js)
        self.assertIn('new URLSearchParams({ limit: "30", project_id: projectId })', js)

    def test_workbench_has_project_workspace_controls(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")

        self.assertIn('id="project-list"', html)
        self.assertIn('id="new-project-button"', html)
        self.assertIn('id="project-home"', html)
        self.assertIn('id="project-new-chat-button"', html)
        self.assertIn('id="project-tab-chats"', html)
        self.assertIn('id="project-tab-sources"', html)
        self.assertIn('id="project-conversation-list"', html)
        self.assertIn('id="project-source-list"', html)
        self.assertIn('id="project-memory-list"', html)
        self.assertIn("projectId", js)
        self.assertIn("loadProjects()", js)
        self.assertIn("openProject", js)
        self.assertIn("renameProjectFromId", js)
        self.assertIn("deleteProjectFromId", js)
        self.assertIn("projectDraftActive", js)
        self.assertIn("currentMessageProjectId", js)
        self.assertIn("startProjectConversation", js)
        self.assertIn("renderProjectHome", js)
        self.assertIn("renderProjectConversationList", js)
        self.assertIn("project-conversation-title-row", js)
        self.assertIn("project-conversation-menu-button", js)
        self.assertIn("openProjectConversationMenu", js)
        project_conversation_menu = js[
            js.index("function openProjectConversationMenu") : js.index("function showContextMenu")
        ]
        self.assertIn("action: () => renameConversationFromPrompt(runId)", project_conversation_menu)
        self.assertNotIn("action: () => startHistoryRename(runId)", project_conversation_menu)
        self.assertIn("renderProjectSourceList", js)
        self.assertIn("deleteProjectSource", js)
        self.assertIn("deleteProjectMemory", js)
        self.assertIn('method: "PATCH"', js)
        self.assertIn('fetch("/api/data-agent/projects?limit=50")', js)
        self.assertIn("project_id: messageProjectId", js)
        self.assertIn("sources/upload", js)
        self.assertIn("hasDatasetProfile", js)
        self.assertIn("项目共享文件已添加", js)
        self.assertIn(".project-panel", css)
        self.assertIn(".project-list", css)
        self.assertIn(".project-item.active", css)
        self.assertIn(".project-menu-button", css)
        self.assertIn(".project-home", css)
        self.assertIn(".project-home-mode .composer-shell", css)
        self.assertIn(".project-new-chat-button", css)
        self.assertIn(".project-tabs", css)
        self.assertIn(".project-conversation-list", css)
        self.assertIn(".project-source-list", css)
        self.assertIn(".project-conversation-menu-button", css)
        self.assertNotIn('id="project-select"', html)
        self.assertNotIn(".project-controls", css)

    def test_workbench_exposes_standalone_agent_monitor_page(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")
        monitor_html = Path("frontend/monitor.html").read_text(encoding="utf-8")
        monitor_js = Path("frontend/monitor.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")
        backend = Path("backend/main.py").read_text(encoding="utf-8")

        self.assertIn('href="/monitor"', html)
        self.assertNotIn('id="monitor-panel"', html)
        self.assertIn('@app.get("/monitor"', backend)
        self.assertIn("workbench_monitor", backend)
        self.assertIn("monitor.html", backend)
        self.assertIn("Agent 节点监看", monitor_html)
        self.assertIn('id="monitor-message-list"', monitor_html)
        self.assertIn('id="monitor-event-list"', monitor_html)
        self.assertIn("对话 / 消息", monitor_html)
        self.assertIn("排查明细", monitor_html)
        self.assertIn("节点解释", monitor_html)
        self.assertIn("安全事件 JSON", monitor_html)
        self.assertIn("已后端脱敏并截断", monitor_html)
        self.assertIn('src="/frontend/monitor.js?v=20260525-agent-monitor"', monitor_html)
        self.assertIn("vds-monitor-runs", monitor_js)
        self.assertIn("monitor_run_id", monitor_js)
        self.assertIn("message_requested", monitor_js)
        self.assertIn("renderMessages", monitor_js)
        self.assertIn("monitorRunRecords", monitor_js)
        self.assertIn("全局监听：/monitor", monitor_js)
        self.assertIn("new EventSource", monitor_js)
        self.assertIn("/api/data-agent/monitor/stream", monitor_js)
        self.assertIn("renderFinalAgentFlow", monitor_js)
        self.assertIn("renderFinalToolCalls", monitor_js)
        self.assertIn("renderNodeExplanations", monitor_js)
        self.assertIn("节点解释：收到 -> 处理 -> 发出", monitor_js)
        self.assertIn("上游：", monitor_js)
        self.assertIn("下游：", monitor_js)
        self.assertIn("收到什么（输入）", monitor_js)
        self.assertIn("干了什么（处理）", monitor_js)
        self.assertIn("发出什么（输出）", monitor_js)
        self.assertIn("查看这个节点的安全事件 JSON", monitor_js)
        self.assertIn("技术 Agent 状态（辅助）", monitor_js)
        self.assertIn("formatJsonPreview", monitor_js)
        self.assertIn(".monitor-dashboard", css)
        self.assertIn(".monitor-node-card", css)
        self.assertIn(".monitor-node-columns", css)
        self.assertIn(".monitor-node-transfer", css)
        self.assertIn(".monitor-message-button", css)
        self.assertIn(".monitor-debug-section", css)
        self.assertIn(".monitor-json", css)


if __name__ == "__main__":
    unittest.main()
