"""Static checks for the backend-mounted workbench shell."""

from __future__ import annotations

import unittest
from pathlib import Path


class WorkbenchStaticAssetsTest(unittest.TestCase):
    def test_workbench_uses_backend_mounted_asset_paths(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")

        self.assertIn('href="/frontend/styles.css?v=20260528-rule-upload-chain-v1"', html)
        self.assertIn('href="/frontend/favicon.svg"', html)
        self.assertIn('src="/frontend/app.js?v=20260528-rule-upload-chain-v1"', html)
        self.assertNotIn('href="./styles.css"', html)
        self.assertNotIn('src="./app.js"', html)

    def test_workbench_assets_are_cache_busted_and_not_cached_by_backend(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")
        backend = Path("backend/main.py").read_text(encoding="utf-8")

        self.assertIn("?v=20260528-rule-upload-chain-v1", html)
        self.assertIn("NO_CACHE_HEADERS", backend)
        self.assertIn('"Cache-Control": "no-store, max-age=0"', backend)
        self.assertIn('"Pragma": "no-cache"', backend)
        self.assertIn('"Expires": "0"', backend)
        self.assertIn("class NoCacheStaticFiles(StaticFiles)", backend)
        self.assertIn("headers=NO_CACHE_HEADERS", backend)

    def test_runtime_sync_preserves_workbench_storage(self) -> None:
        script = Path("scripts/sync_workbench_runtime.sh").read_text(encoding="utf-8")

        self.assertIn('--exclude "/storage/"', script)
        self.assertNotIn('--exclude "storage"', script)
        self.assertIn("--delete", script)

    def test_visualization_dependencies_include_matplotlib(self) -> None:
        requirements = Path("requirements-visualization.txt").read_text(encoding="utf-8")
        script = Path("scripts/run_workbench_server.sh").read_text(encoding="utf-8")

        self.assertIn("matplotlib>=3.8", requirements)
        self.assertIn('("matplotlib>=3.8", "matplotlib")', script)

    def test_workbench_chart_svg_overrides_global_icon_svg_size(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")

        self.assertIn("const displayValues = values.slice(0, horizontal ? 18 : 16)", js)
        self.assertIn("chartTicks(domain.min, domain.max, 5)", js)
        self.assertIn("chartTooltip({", js)
        self.assertIn("resolveLineSeries(chart, rows, x, y, fallbackColumns)", js)
        self.assertIn("bindChartInteractions(el.chartPanel)", js)
        self.assertIn('panel.addEventListener("pointerover", activateFromEvent)', js)
        self.assertIn(".chart-svg", css)
        self.assertIn("height: auto;", css)
        self.assertIn("max-height: none;", css)
        self.assertIn("min-height: 300px;", css)
        self.assertIn(".chart-hover-card", css)
        self.assertIn(".chart-hit.is-active .chart-hover-card", css)
        self.assertIn(".chart-legend-label", css)
        self.assertIn("pointer-events: all;", css)
        self.assertIn(".axis-title", css)
        self.assertIn("font-synthesis: none;", css)
        self.assertIn("font-weight: 400 !important;", css)
        self.assertIn("function resolveLineYAxisName", js)

    def test_workbench_prefers_interactive_chart_svg_over_backend_images(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")
        render_chart = js.split("function renderChart", 1)[1].split("function renderChartImage", 1)[0]

        self.assertIn("chart?.image_data_uri", js)
        self.assertIn("renderChartImage", js)
        self.assertLess(render_chart.index("const y = resolveChartY"), render_chart.index("chart?.image_data_uri"))
        self.assertIn("renderBarChart(values, chart", js)
        self.assertIn("renderLineChart(seriesValues, chart)", js)
        self.assertIn('class="chart-image"', js)
        self.assertIn("function resolveChartY", js)
        self.assertIn(".chart-image", css)
        self.assertIn("object-fit: contain;", css)

    def test_activity_drawer_scrolls_to_latest_activity(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")

        self.assertIn("activityDrawerAutoScroll: true", js)
        self.assertIn("renderActivityDrawer(state.drawerResult, { scrollToLatest: true })", js)
        self.assertIn("function scrollActivityDrawerToLatest()", js)
        self.assertIn("el.activityDrawerList.scrollTop = el.activityDrawerList.scrollHeight", js)
        self.assertIn("function handleActivityDrawerScroll()", js)

    def test_workbench_uses_chat_first_shell(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")

        self.assertIn('aria-label="历史 Chat"', html)
        self.assertIn('id="chat-messages"', html)
        self.assertIn('href="/monitor"', html)
        self.assertIn('id="dataset-status" class="hidden" aria-hidden="true"', html)
        self.assertIn('class="composer-shell"', html)
        self.assertIn('class="composer-input is-empty"', html)
        self.assertIn('role="textbox"', html)
        self.assertIn('contenteditable="plaintext-only"', html)
        self.assertIn('data-placeholder="向 VDS 提问，例如：哪个城市订单金额最高？"', html)
        self.assertIn('spellcheck="false"', html)
        self.assertIn('data-ms-editor="false"', html)
        self.assertIn('data-enable-grammarly="false"', html)
        self.assertIn('class="upload-controls"', html)
        self.assertIn('id="upload-button"', html)
        self.assertIn('id="file-summary"', html)
        self.assertIn('id="file-panel"', html)
        self.assertIn('class="file-panel-list"', html)
        topbar = html.split('<header class="chat-topbar">', 1)[1].split("</header>", 1)[0]
        composer = html.split('<section class="composer-shell"', 1)[1].split('<div class="controls-row">', 1)[0]
        self.assertIn('id="file-status-wrap"', topbar)
        self.assertIn("查看文件", topbar)
        self.assertNotIn('id="file-status-wrap"', composer)
        self.assertIn('id="rule-file-input"', html)
        self.assertIn('id="rule-upload-button"', html)
        self.assertIn("上传数据文件", html)
        self.assertIn("添加规则", html)
        self.assertIn('id="rule-file-status" class="rule-file-status is-empty"', html)
        self.assertIn("可选：上传规则文件可以补充语义模型、指标口径和计算方法", html)
        self.assertIn('accept=".csv,.xlsx,.xls,.json,.parquet,.arrow,.feather,.md,.txt,.yaml,.yml,.doc,.docx,.docm,.rtf,.odt,.pdf,.pages,.html,.htm"', html)
        self.assertIn("上传数据文件，然后直接提问", html)
        self.assertNotIn("高级选项", html)
        self.assertNotIn("启用 Rule Mode", html)
        self.assertNotIn("选择分析规则", html)
        self.assertNotIn("选择 Benchmark 规则", html)
        self.assertNotIn('id="benchmark-rule-input"', html)
        self.assertNotIn('id="benchmark-run-button"', html)
        self.assertNotIn('class="upload-card"', html)
        self.assertNotIn('id="dropzone"', html)
        self.assertNotIn("<textarea", html)
        self.assertNotIn('class="work-grid"', html)
        self.assertNotIn('class="inspector"', html)

    def test_workbench_has_chat_search_overlay(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")

        self.assertIn('id="chat-search-button"', html)
        self.assertIn("搜索聊天", html)
        self.assertIn('id="chat-search-dialog"', html)
        self.assertIn('placeholder="搜索聊天..."', html)
        self.assertIn('id="chat-search-results"', html)
        self.assertIn("openChatSearch", js)
        self.assertIn("renderChatSearchResults", js)
        self.assertIn("chatSearchGroupLabel", js)
        self.assertIn("loadConversation(runId)", js)
        self.assertIn(".chat-search-dialog", css)
        self.assertIn(".chat-search-card", css)
        self.assertIn(".chat-search-result", css)

    def test_workbench_rule_package_support_stays_backend_routed_and_hidden_from_ui(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")

        self.assertIn('accept=".csv,.xlsx,.xls,.json,.parquet,.arrow,.feather,.md,.txt,.yaml,.yml,.doc,.docx,.docm,.rtf,.odt,.pdf,.pages,.html,.htm"', html)
        self.assertNotIn("DAB 规则包", html)
        self.assertNotIn("DAB 规则包", js)
        self.assertIn('"/api/data-agent/upload-batch"', js)
        self.assertIn("renderFilePanel", js)
        self.assertIn("buildReadyFileRecords", js)
        self.assertIn("backendUploadedFileRecords", js)
        self.assertIn("uploaded_files", js)
        self.assertIn("uniqueSourceFileNames", js)
        self.assertIn("boundRuleFileNames", js)
        self.assertIn("查看文件", js)
        self.assertIn("ATTACHED_FILE_QUESTION_PLACEHOLDER", js)
        self.assertIn("RULE_FILE_STATUS_TONES", js)
        self.assertIn('setRuleFileStatus(`规则上传失败：${String(error.message || error)}`, "error")', js)
        self.assertIn("const showComposerFiles = state.hasPendingUpload && hasRecords", js)
        self.assertIn("renderComposerFileTray(showComposerFiles ? records : [])", js)
        self.assertIn(".composer.has-files", css)
        self.assertIn("grid-template-columns: 34px auto minmax(180px, 1fr) 36px", css)
        self.assertIn(".composer.has-files .rule-file-button", css)
        self.assertIn(".rule-file-status.is-error", css)
        self.assertIn("grid-row: 3", css)
        self.assertIn("border-left: 1px solid #d1d5db", css)
        self.assertIn("来源文件已就绪", js)
        self.assertNotIn("fees.json", js)
        self.assertNotIn("merchant_data.json", js)
        self.assertNotIn("manual.md", js)

    def test_workbench_renders_backend_execution_artifacts(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")

        self.assertIn("artifact-panel", html)
        self.assertIn("artifact-list", html)
        self.assertIn("renderExecutionArtifacts", js)
        self.assertIn("result.execution_artifacts", js)
        self.assertIn("renderExecutionArtifacts(result.execution_artifacts || [])", js)
        self.assertIn("renderArtifactCards(artifacts)", js)
        self.assertIn("复现代码", js)
        self.assertIn("el.artifactPanel?.classList.add(\"hidden\")", js)
        self.assertIn(".artifact-card", css)
        self.assertIn(".artifact-list.inline", css)
        self.assertIn("white-space: pre-wrap", css)
        self.assertIn(".activity-artifact-card code", css)
        self.assertIn("overflow-wrap: anywhere", css)

    def test_workbench_renders_answer_source_footer(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")

        self.assertIn("answer-source-panel", html)
        self.assertIn("回答来源", html)
        self.assertIn(">来源<", html)
        self.assertIn("source_references", js)
        self.assertIn("renderAnswerSources(result)", js)
        self.assertIn("deriveAnswerSourcesFromProfile", js)
        self.assertIn("refreshRenderedAnswerSources", js)
        self.assertIn(".answer-source-list", css)
        self.assertIn(".answer-source-icon.spreadsheet", css)

    def test_workbench_insight_next_step_prefers_actionable_advice(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")

        self.assertIn("function resolveInsightAdviceCandidates", js)
        self.assertIn("const directSuggestions = [insight?.next_step", js)
        self.assertIn("return uniqueStrings([...directSuggestions, ...businessSuggestions])", js)
        self.assertIn("function isDistinctInsightText", js)
        self.assertIn("normalizeInsightText(value) !== normalizeInsightText(summary)", js)
        self.assertIn("const rawAdvice = isActionableInsightAdvice(advice) ? advice : \"\"", js)

    def test_workbench_suppresses_raw_detail_rows_for_general_questions(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")

        self.assertIn("function shouldRenderRows", js)
        self.assertIn('result.answer_type === "overview"', js)
        self.assertIn('result.answer_type === "cleaning_simulation"', js)
        self.assertIn("looksLikeGeneralQuestion", js)
        self.assertIn("tooWideForMainAnswer", js)
        self.assertIn("主要讲什么", js)
        self.assertIn("影响行数", js)
        self.assertIn("renderInsightBody", js)
        self.assertIn("<strong>下一步：</strong>", js)
        self.assertIn("<strong>可继续问：</strong>", js)
        self.assertIn("rowsWithoutContinuationPrompts(rawRows)", js)
        self.assertIn("function isContinuationPromptRow", js)
        self.assertIn('const CONTINUATION_PROMPT_LABELS = ["可继续提问"', js)
        self.assertIn("isRowDescriptorColumn", js)
        self.assertIn("pickInsightAdvice", js)
        self.assertIn("buildContextualNextQuestions", js)
        self.assertIn("isGenericNextQuestionSet", js)
        self.assertIn("renderInsight(!isChat && result.success ? result.insight : null, result)", js)
        self.assertNotIn("renderInsightCard", js)
        self.assertNotIn(".insight-card", css)

    def test_workbench_hides_backend_audit_panels_from_user_shell(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")

        self.assertIn("分析过程", html)
        self.assertNotIn("数据质量", html)
        self.assertNotIn("Join / Verification", html)
        self.assertNotIn("Warnings / Errors", html)
        self.assertNotIn("source_tables", html)
        self.assertNotIn("join_plan", html)
        self.assertNotIn("dataset_id:", html)

    def test_workbench_renders_safe_process_evidence_from_backend(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")

        self.assertIn("normalizeProcessList(step.evidence", js)
        self.assertIn("renderProcessEvidence(step)", js)
        self.assertIn('aria-label="过程依据"', js)
        self.assertIn("connectActivityStream", js)
        self.assertIn("new EventSource", js)
        self.assertIn("/api/data-agent/monitor/stream?monitor_run_id=", js)
        self.assertIn("ACTIVITY_EVENT_TYPES", js)
        self.assertIn("code_artifact_ready", js)
        self.assertIn("activity_trace_delta", js)
        self.assertIn("agent_failed", js)
        self.assertIn("correction_rerun_started", js)
        self.assertIn("activityNodeFromMonitorEvent", js)
        self.assertIn("liveActivitySummaryFromEvent", js)
        self.assertIn("activityRoleCompletionSummary", js)
        self.assertIn("已锁定数据集", js)
        self.assertIn("避免拿错文件回答", js)
        self.assertIn("normalizeActivityTrace", js)
        self.assertIn(".process-evidence", css)
        self.assertNotIn("buildFriendlySteps(processSource", js)

    def test_workbench_opens_activity_drawer_from_thinking_summary(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")

        self.assertIn('id="activity-drawer"', html)
        self.assertIn('id="activity-backdrop"', html)
        self.assertIn('aria-controls="activity-drawer"', html)
        self.assertIn('aria-haspopup="dialog"', html)
        self.assertNotIn("activity-open-button", html)
        self.assertIn("handleThinkingSummaryClick", js)
        self.assertIn("handleThinkingSummaryKeydown", js)
        self.assertIn("updateThinkingSummaryExpanded", js)
        self.assertIn("details.open = false", js)
        self.assertIn('el.activityDrawerTitle.textContent = "思考与执行链路"', js)
        self.assertIn(".process-details summary", js)
        self.assertIn("openActivityDrawer", js)
        self.assertIn("buildActivityDrawerSections", js)
        self.assertIn("buildDrawerActivityTrace", js)
        self.assertIn("renderActivityNodeDigest", js)
        self.assertIn("activityNodeDigest", js)
        self.assertIn("收到什么（输入）", js)
        self.assertIn("干了什么（处理）", js)
        self.assertIn("发出什么（输出）", js)
        self.assertIn("上游：", js)
        self.assertIn("计划节点决定后面按什么口径计算", js)
        self.assertNotIn("renderInlineActivityTrace", js)
        self.assertNotIn("process-activity-list", js)
        self.assertIn("activity_trace_v2", js)
        self.assertIn("process-summary-text", html)
        self.assertIn('class="process-summary-text" aria-hidden="true"', html)
        self.assertIn("liveSummary: true", js)
        self.assertIn("function oneLineProcessSummary", js)
        self.assertIn("has-live-summary", js)
        self.assertIn("message.querySelector(\".process-summary-text, #process-summary\")", js)
        self.assertIn(".activity-drawer-section", css)
        self.assertIn(".activity-section-list", css)
        self.assertIn(".activity-node", css)
        self.assertIn(".activity-node-transfer", css)
        self.assertIn(".activity-node-columns", css)
        self.assertIn(".activity-node-box", css)
        self.assertIn(".activity-artifact-card", css)
        self.assertIn(".process-details.has-live-summary", css)
        self.assertIn(".process-timeline {\n  display: none;", css)

    def test_workbench_allows_chat_without_uploaded_dataset(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")

        self.assertIn('"/api/data-agent/message"', js)
        self.assertIn('answer_type === "chat"', js)
        self.assertNotIn("!state.datasetId || !question", js)
        self.assertNotIn('state.datasetId ? "/api/data-agent/analyze"', js)
        self.assertIn("当前没有上传数据，我会直接回复可讨论的部分，不编造业务结论。", js)

    def test_workbench_filters_english_insight_leaks_from_history(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")

        self.assertIn("function looksLikeEnglishProseLeak", js)
        self.assertIn("function segmentLooksLikeEnglishProseLeak", js)
        self.assertIn("function isActionableInsightAdvice", js)
        self.assertIn("function buildContextualInsightSummary", js)
        self.assertIn("排名结果里第 1 位是", js)
        self.assertIn('if (!/[\\u3400-\\u9fff]/.test(value)) return false;', js)
        self.assertIn("(?:观察|风险|边界|依据|建议|下一步)", js)
        self.assertIn('"ranking"', js)
        self.assertIn('"countries"', js)
        self.assertIn("proseCount >= 2", js)
        self.assertIn("isActionableInsightAdvice(parsed.action)", js)

    def test_workbench_keeps_dataset_filename_out_of_topbar(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")
        js = Path("frontend/app.js").read_text(encoding="utf-8")

        self.assertIn('id="dataset-status" class="hidden" aria-hidden="true"', html)
        self.assertIn("clearDatasetHeaderStatus", js)
        render_profile = js[js.index("function renderProfile()") : js.index("function clearDatasetHeaderStatus")]
        self.assertIn("clearDatasetHeaderStatus()", render_profile)
        self.assertNotIn("profile.file_name", render_profile)
        self.assertNotIn("datasetStatus.textContent", render_profile)

    def test_workbench_creates_one_assistant_result_per_turn(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")

        self.assertIn("createAssistantResultMessage", js)
        self.assertIn("cloneNode(true)", js)
        self.assertIn("assistant-result-message", js)
        self.assertIn(".assistant-message.thinking-only .result-panel", css)

    def test_workbench_enter_sends_and_shift_enter_keeps_newline(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")

        self.assertIn('addEventListener("keydown", handleQuestionKeydown)', js)
        self.assertIn('addEventListener("input", handleQuestionInput)', js)
        self.assertIn('addEventListener("paste", handleQuestionPaste)', js)
        self.assertIn('addEventListener("focus", updateQuestionEmptyState)', js)
        self.assertIn("getQuestionText()", js)
        self.assertIn("setQuestionText(\"\")", js)
        self.assertIn("updateQuestionEmptyState()", js)
        self.assertNotIn("questionInput.value", js)
        self.assertIn('event.key !== "Enter" || event.shiftKey || event.isComposing', js)
        self.assertIn("event.preventDefault()", js)
        self.assertIn("runAnalysis()", js)

    def test_workbench_history_items_can_be_renamed(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")

        self.assertIn("renderHistory()", js)
        self.assertIn("startHistoryRename", js)
        self.assertIn("commitHistoryRename", js)
        self.assertIn("handleHistoryRenameKeydown", js)
        self.assertIn("history-rename-button", js)
        self.assertIn("history-menu-button", js)
        self.assertIn("history-rename-input", js)
        self.assertIn("history-project-button", js)
        self.assertIn("history-delete-button", js)
        self.assertIn("history-pin-button", js)
        self.assertIn("toggleHistoryPinned", js)
        self.assertIn("renameConversationFromPrompt", js)
        self.assertIn("sortHistoryItems", js)
        self.assertIn("pinIcon", js)
        self.assertIn("openHistoryMenu", js)
        self.assertIn("openTextDialog", js)
        self.assertIn("closeTextDialog", js)
        self.assertIn("submitTextDialog", js)
        self.assertNotIn("window.prompt", js)
        self.assertIn("buildProjectMoveItems", js)
        self.assertIn("renderContextSubmenu", js)
        self.assertIn("showContextSubmenu", js)
        self.assertIn("createProjectForHistory", js)
        self.assertIn("assignHistoryToProject", js)
        move_project_create = js[js.index("async function createProjectForHistory") : js.index("async function assignHistoryToProject")]
        self.assertIn('body: JSON.stringify({ name: "新项目" })', move_project_create)
        self.assertNotIn("window.prompt", move_project_create)
        self.assertIn("deleteHistoryConversation", js)
        self.assertIn("body: JSON.stringify({ pinned: Boolean(pinned) })", js)
        self.assertIn('body: JSON.stringify({ project_id: safeProjectId })', js)
        self.assertNotIn("chooseProjectForHistory", js)
        self.assertNotIn("选择要移入的 Project", js)
        self.assertIn('method: "DELETE"', js)
        self.assertIn("markHistoryRunning", js)
        self.assertIn("acknowledgeHistoryItem", js)
        self.assertIn("unread: existing?.unread === true", js)
        self.assertIn("existingById", js)
        self.assertIn("localUnreadHistory", js)
        self.assertNotIn("已完成分析", js)
        self.assertNotIn("history-state", js)
        self.assertNotIn("hasVisibleState", js)
        self.assertNotIn("thinking-dot", js)
        self.assertIn('event.key === "Enter"', js)
        self.assertIn('event.key === "Escape"', js)
        self.assertIn("dataset.cancelRename", js)
        self.assertIn('input.addEventListener("blur"', js)
        self.assertIn('fetch(`/api/data-agent/conversations/${encodeURIComponent(runId)}`', js)
        self.assertIn(".history-item", css)
        self.assertIn(".history-item.active", css)
        self.assertIn("status-pill", css)
        self.assertIn(".button.primary:disabled", css)
        self.assertIn("background: #e5e7eb;", css)
        self.assertIn("border-color: #b8bbc7;", css)
        self.assertIn(".composer-input:empty::before", css)
        self.assertIn(".composer-input:empty", css)
        self.assertIn(".composer-input.is-empty", css)
        self.assertIn("caret-color: transparent;", css)
        self.assertIn("text-indent: -9999px;", css)
        self.assertIn("-webkit-text-fill-color: transparent;", css)
        self.assertIn(".composer-input:not(:empty)", css)
        self.assertIn("caret-color: #111827;", css)
        self.assertIn("grammarly-desktop-integration", css)
        self.assertIn("ms-editor-squiggler", css)
        self.assertNotIn("box-shadow: 0 18px 50px rgba(37, 99, 235", css)
        self.assertNotIn("status-dot", html)
        self.assertNotIn("status-dot", js)
        self.assertNotIn("status-spin", css)
        self.assertNotIn(".history-item.has-state", css)
        self.assertNotIn(".history-state", css)
        self.assertNotIn("thinking-dot", css)
        self.assertNotIn("step-dot", js)
        self.assertNotIn(".step-dot", css)
        self.assertIn(".history-menu-button", css)
        self.assertIn(".context-menu", css)
        self.assertIn(".context-submenu", css)
        self.assertIn(".context-menu-chevron", css)
        self.assertIn(".dialog-overlay", css)
        self.assertIn(".text-dialog-card", css)
        self.assertIn(".pin-indicator", css)
        self.assertIn(".history-rename-input", css)
        self.assertIn(".history-item.editing .history-title-row", css)
        self.assertIn("message-meta", html)
        self.assertIn("message-meta", css)
        self.assertIn("thinking-elapsed", html)
        self.assertIn("thinking-elapsed", css)
        self.assertIn("copy-reply-button", html)
        self.assertIn("copy-reply-button", css)
        self.assertIn("copyReplyFromMessage", js)
        self.assertIn("selectReplyText", js)
        self.assertIn("copyReplyIcon", js)
        self.assertIn("checkReplyIcon", js)
        self.assertIn("data-tooltip", html)
        self.assertIn("content: attr(data-tooltip)", css)
        self.assertIn("navigator.clipboard.writeText", js)
        self.assertIn("document.execCommand(\"copy\")", js)
        self.assertNotIn("copy-reply-button.copied {\n  background: rgba(21, 128, 61", css)

    def test_workbench_loads_persistent_conversations(self) -> None:
        js = Path("frontend/app.js").read_text(encoding="utf-8")

        self.assertIn("conversationId", js)
        self.assertIn("loadConversations()", js)
        self.assertIn("new URLSearchParams", js)
        self.assertIn("`/api/data-agent/conversations?${query.toString()}`", js)
        self.assertIn("loadConversation", js)
        self.assertIn("restoreConversation", js)
        self.assertIn("applyRestoredFileRecords(profile)", js)
        self.assertIn("clearRestoredFileRecords()", js)
        self.assertIn("state.fileRecords.length} 个文件已就绪", js)
        self.assertIn("文件信息不可用", js)
        self.assertIn('item.last_answer_type === "chat" ? "chat" : "analysis"', js)
        self.assertIn("conversation_id: state.conversationId", js)
        self.assertIn("updateHistory: false", js)
        self.assertIn("createdAt: message.created_at", js)
        self.assertIn("thinking_elapsed_ms", js)
        self.assertIn("pinned: Boolean(item.pinned)", js)
        self.assertIn("pinnedAt: item.pinned_at ||", js)
        global_loader = js[js.index("async function loadConversations()") : js.index("async function loadConversation(")]
        self.assertNotIn('query.set("project_id"', global_loader)
        self.assertNotIn('new URLSearchParams({ limit: "30", project_id', global_loader)
        self.assertIn(".filter((item) => !item.project_id)", global_loader)
        self.assertIn("!item.projectId && !loadedIds.has(item.runId)", global_loader)
        self.assertIn("loadProjectConversations", js)
        self.assertIn('new URLSearchParams({ limit: "30", project_id: projectId })', js)

    def test_workbench_has_project_workspace_controls(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")
        js = Path("frontend/app.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")

        self.assertIn('id="project-list"', html)
        self.assertIn('id="project-collapse-button"', html)
        self.assertIn('aria-controls="project-section-body"', html)
        self.assertIn('id="project-section-body"', html)
        self.assertIn('id="new-project-button"', html)
        self.assertIn('id="text-dialog"', html)
        self.assertIn('id="text-dialog-input"', html)
        self.assertIn('id="project-home"', html)
        self.assertIn('id="project-new-chat-button"', html)
        self.assertIn('id="project-tab-chats"', html)
        self.assertIn('id="project-tab-sources"', html)
        self.assertIn('id="project-conversation-list"', html)
        self.assertIn('id="project-source-upload-input"', html)
        self.assertIn('id="project-source-upload-dropzone"', html)
        self.assertIn('id="project-source-upload-status"', html)
        self.assertIn('id="project-source-list"', html)
        self.assertIn('id="project-memory-list"', html)
        self.assertIn("projectId", js)
        self.assertIn("loadProjects()", js)
        self.assertIn("PROJECT_PANEL_COLLAPSED_KEY", js)
        self.assertIn("loadProjectPanelCollapsed", js)
        self.assertIn("toggleProjectPanelCollapsed", js)
        self.assertIn("renderProjectPanelCollapsed", js)
        self.assertIn("openProject", js)
        self.assertIn("renameProjectFromId", js)
        self.assertIn("deleteProjectFromId", js)
        self.assertIn("projectDraftActive", js)
        self.assertIn("currentMessageProjectId", js)
        self.assertIn("markHistoryRunning(question, monitorRunId, messageProjectId)", js)
        self.assertIn("markHistoryFailed(question, String(error.message || error), messageProjectId)", js)
        self.assertIn("startProjectConversation", js)
        self.assertIn("renderProjectHome", js)
        self.assertIn("renderProjectConversationList", js)
        self.assertIn("project-conversation-title-row", js)
        self.assertIn("project-conversation-menu-button", js)
        self.assertIn("openProjectConversationMenu", js)
        project_conversation_menu = js[
            js.index("function openProjectConversationMenu") : js.index("function showContextMenu")
        ]
        self.assertIn("action: () => renameConversationFromPrompt(runId)", project_conversation_menu)
        self.assertNotIn("action: () => startHistoryRename(runId)", project_conversation_menu)
        self.assertIn("renderProjectSourceList", js)
        self.assertIn("buildProjectSourceRows", js)
        self.assertIn("projectSourceFileNames", js)
        self.assertIn("spreadsheetSourceIcon", js)
        self.assertIn("project-source-menu-button", js)
        self.assertIn("uploadProjectSourceFiles", js)
        self.assertIn("handleProjectSourceDrop", js)
        self.assertIn("projectSourceUploadDropzone", js)
        self.assertIn("deleteProjectSource", js)
        self.assertIn("deleteProjectMemory", js)
        self.assertIn('method: "PATCH"', js)
        self.assertIn('fetch("/api/data-agent/projects?limit=50")', js)
        self.assertIn("project_id: messageProjectId", js)
        self.assertIn("sources/upload", js)
        self.assertIn("hasDatasetProfile", js)
        self.assertIn("项目共享文件已添加", js)
        self.assertIn(".project-panel", css)
        self.assertIn(".project-header-button", css)
        self.assertIn(".project-collapse-icon", css)
        self.assertIn(".project-panel.collapsed", css)
        self.assertIn(".project-section-body", css)
        self.assertIn(".project-list", css)
        self.assertIn(".project-item.active", css)
        self.assertIn(".project-menu-button", css)
        self.assertIn(".project-home", css)
        self.assertIn(".project-home-mode .composer-shell", css)
        self.assertIn(".project-new-chat-button", css)
        self.assertIn(".project-tabs", css)
        self.assertIn(".project-source-upload-dropzone", css)
        self.assertIn(".project-source-upload-status", css)
        self.assertIn(".project-source-item.dataset-group", css)
        self.assertIn(".project-source-item.file-source", css)
        self.assertIn(".project-source-row-icon.spreadsheet", css)
        self.assertIn(".project-conversation-list", css)
        self.assertIn(".project-source-list", css)
        self.assertIn(".project-conversation-menu-button", css)
        self.assertNotIn('id="project-select"', html)
        self.assertNotIn(".project-controls", css)

    def test_workbench_exposes_standalone_agent_monitor_page(self) -> None:
        html = Path("frontend/index.html").read_text(encoding="utf-8")
        monitor_html = Path("frontend/monitor.html").read_text(encoding="utf-8")
        monitor_js = Path("frontend/monitor.js").read_text(encoding="utf-8")
        css = Path("frontend/styles.css").read_text(encoding="utf-8")
        backend = Path("backend/main.py").read_text(encoding="utf-8")

        self.assertIn('href="/monitor"', html)
        self.assertNotIn('id="monitor-panel"', html)
        self.assertIn('@app.get("/monitor"', backend)
        self.assertIn("workbench_monitor", backend)
        self.assertIn("monitor.html", backend)
        self.assertIn("Agent 节点监看", monitor_html)
        self.assertIn('id="monitor-message-list"', monitor_html)
        self.assertIn('id="monitor-event-list"', monitor_html)
        self.assertIn("对话 / 消息", monitor_html)
        self.assertIn("排查明细", monitor_html)
        self.assertIn("节点解释", monitor_html)
        self.assertIn("安全事件 JSON", monitor_html)
        self.assertIn("已后端脱敏并截断", monitor_html)
        self.assertIn('src="/frontend/monitor.js?v=20260525-agent-monitor"', monitor_html)
        self.assertIn("vds-monitor-runs", monitor_js)
        self.assertIn("monitor_run_id", monitor_js)
        self.assertIn("message_requested", monitor_js)
        self.assertIn("renderMessages", monitor_js)
        self.assertIn("monitorRunRecords", monitor_js)
        self.assertIn("全局监听：/monitor", monitor_js)
        self.assertIn("new EventSource", monitor_js)
        self.assertIn("/api/data-agent/monitor/stream", monitor_js)
        self.assertIn("renderFinalAgentFlow", monitor_js)
        self.assertIn("renderFinalToolCalls", monitor_js)
        self.assertIn("renderNodeExplanations", monitor_js)
        self.assertIn("节点解释：收到 -> 处理 -> 发出", monitor_js)
        self.assertIn("上游：", monitor_js)
        self.assertIn("下游：", monitor_js)
        self.assertIn("收到什么（输入）", monitor_js)
        self.assertIn("干了什么（处理）", monitor_js)
        self.assertIn("发出什么（输出）", monitor_js)
        self.assertIn("查看这个节点的安全事件 JSON", monitor_js)
        self.assertIn("技术 Agent 状态（辅助）", monitor_js)
        self.assertIn("formatJsonPreview", monitor_js)
        self.assertIn(".monitor-dashboard", css)
        self.assertIn(".monitor-node-card", css)
        self.assertIn(".monitor-node-columns", css)
        self.assertIn(".monitor-node-transfer", css)
        self.assertIn(".monitor-message-button", css)
        self.assertIn(".monitor-debug-section", css)
        self.assertIn(".monitor-json", css)


if __name__ == "__main__":
    unittest.main()
